/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SecondaryMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyShares"
      | "cancelListing"
      | "listShares"
      | "listingCounter"
      | "listings"
      | "owner"
      | "renounceOwnership"
      | "talentShareToken"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ListingCanceled"
      | "OwnershipTransferred"
      | "SharesListed"
      | "SharesSold"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyShares",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelListing",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listShares",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "listingCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "listings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "talentShareToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "buyShares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelListing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listShares", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "listingCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "listings", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "talentShareToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ListingCanceledEvent {
  export type InputTuple = [listingId: BigNumberish];
  export type OutputTuple = [listingId: bigint];
  export interface OutputObject {
    listingId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesListedEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    seller: AddressLike,
    tokenId: BigNumberish,
    price: BigNumberish,
    quantity: BigNumberish
  ];
  export type OutputTuple = [
    listingId: bigint,
    seller: string,
    tokenId: bigint,
    price: bigint,
    quantity: bigint
  ];
  export interface OutputObject {
    listingId: bigint;
    seller: string;
    tokenId: bigint;
    price: bigint;
    quantity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SharesSoldEvent {
  export type InputTuple = [
    listingId: BigNumberish,
    buyer: AddressLike,
    quantity: BigNumberish
  ];
  export type OutputTuple = [
    listingId: bigint,
    buyer: string,
    quantity: bigint
  ];
  export interface OutputObject {
    listingId: bigint;
    buyer: string;
    quantity: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SecondaryMarket extends BaseContract {
  connect(runner?: ContractRunner | null): SecondaryMarket;
  waitForDeployment(): Promise<this>;

  interface: SecondaryMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyShares: TypedContractMethod<
    [listingId: BigNumberish, quantityToBuy: BigNumberish],
    [void],
    "payable"
  >;

  cancelListing: TypedContractMethod<
    [listingId: BigNumberish],
    [void],
    "nonpayable"
  >;

  listShares: TypedContractMethod<
    [tokenId: BigNumberish, price: BigNumberish, quantity: BigNumberish],
    [void],
    "nonpayable"
  >;

  listingCounter: TypedContractMethod<[], [bigint], "view">;

  listings: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, boolean] & {
        id: bigint;
        seller: string;
        tokenId: bigint;
        price: bigint;
        quantity: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  talentShareToken: TypedContractMethod<[], [string], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyShares"
  ): TypedContractMethod<
    [listingId: BigNumberish, quantityToBuy: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "cancelListing"
  ): TypedContractMethod<[listingId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "listShares"
  ): TypedContractMethod<
    [tokenId: BigNumberish, price: BigNumberish, quantity: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "listingCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "listings"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, boolean] & {
        id: bigint;
        seller: string;
        tokenId: bigint;
        price: bigint;
        quantity: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "talentShareToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ListingCanceled"
  ): TypedContractEvent<
    ListingCanceledEvent.InputTuple,
    ListingCanceledEvent.OutputTuple,
    ListingCanceledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "SharesListed"
  ): TypedContractEvent<
    SharesListedEvent.InputTuple,
    SharesListedEvent.OutputTuple,
    SharesListedEvent.OutputObject
  >;
  getEvent(
    key: "SharesSold"
  ): TypedContractEvent<
    SharesSoldEvent.InputTuple,
    SharesSoldEvent.OutputTuple,
    SharesSoldEvent.OutputObject
  >;

  filters: {
    "ListingCanceled(uint256)": TypedContractEvent<
      ListingCanceledEvent.InputTuple,
      ListingCanceledEvent.OutputTuple,
      ListingCanceledEvent.OutputObject
    >;
    ListingCanceled: TypedContractEvent<
      ListingCanceledEvent.InputTuple,
      ListingCanceledEvent.OutputTuple,
      ListingCanceledEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "SharesListed(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      SharesListedEvent.InputTuple,
      SharesListedEvent.OutputTuple,
      SharesListedEvent.OutputObject
    >;
    SharesListed: TypedContractEvent<
      SharesListedEvent.InputTuple,
      SharesListedEvent.OutputTuple,
      SharesListedEvent.OutputObject
    >;

    "SharesSold(uint256,address,uint256)": TypedContractEvent<
      SharesSoldEvent.InputTuple,
      SharesSoldEvent.OutputTuple,
      SharesSoldEvent.OutputObject
    >;
    SharesSold: TypedContractEvent<
      SharesSoldEvent.InputTuple,
      SharesSoldEvent.OutputTuple,
      SharesSoldEvent.OutputObject
    >;
  };
}
